ALTER TABLE usuario ADD COLUMN email    VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE usuario ADD COLUMN password VARCHAR(200) NOT NULL DEFAULT '';

ALTER TABLE usuario ADD CONSTRAINT uq_usuario_email UNIQUE (email);
